### ISSUE TITLE
Gear QC with position

### ISSUE THREAD

**Issue by cmspinto** [ices-eg/wg_WGDEC#15]
Data centre to add new automated check - if trawl, towed camera or ROV codes (from list provided) are used, and no start/end lat/long provided - produce a warning

**Comment by laurar97** [comment]
Answer: please use these codes: AGT; BAK; BMT; BOT; GOC73; GOV; GRT; NCT; JDT; ROT; SIDC; SIROV; SITC; TVL;TVS; UD; VID-DROP; VID-TOW

**Comment by Osanna123** [comment]
Check 1931 together with cross-checks on position
