### ISSUE TITLE
Extraction headings

### ISSUE THREAD

**Issue by cmspinto** [ices-eg/wg_WGDEC#17]
Data centre to change the headings in the extract so they match the exact headings used in the VME reporting template (e.g. SurveyMethod should be DataCollectionMethod)

**Comment by Osanna123** [comment]
@cmspinto do you need help with this task?

**Comment by Osanna123** [comment]
The task can be reopened if needed

**Comment by cmspinto** [comment]
I don't understand the task here, sorry.

**Comment by david9317** [comment]
I think it was closed due to its age, Carlos... We can open it again if it's still an issue in the post-wgdec meeting with the data centre.
