### ISSUE TITLE
list of commonly used trawl

### ISSUE THREAD

**Issue by cmspinto** [ices-eg/wg_WGDEC#20]
Laura to send Anna a list of commonly used trawl, towed camera and ROV SMTYP codes

**Comment by laurar97** [comment]
Answer: please use these codes: AGT; BAK; BMT; BOT; GOC73; GOV; GRT; NCT; JDT; ROT; SIDC; SIROV; SITC; TVL;TVS; UD; VID-DROP; VID-TOW;

**Comment by cmspinto** [comment]
@Osanna123 can you check this

**Comment by Osanna123** [comment]
Apologies, i have a question: is this related to https://github.com/ices-eg/wg_WGDEC/issues/15, or has another purpose?

**Comment by laurar97** [comment]
Yes it's related to #15 - I think we just had two actions as one was on me and one was on you. We can remove this one now.
