### ISSUE TITLE
VME API

### ISSUE THREAD

**Issue by cmspinto** [ices-eg/wg_WGDEC#23]
There is a new API for the VME database. 

The services are described here:
https://vme.ices.dk/webservices.aspx

It is now possible to ask for a token and to access the restricted data using the WebAPI

**Comment by NauticalNeil** [comment]
Hi @cmspinto - following the instructions you provided to @laurar97 , I installed Postman and attempted to request a token from https://vme.ices.dk/webservices.aspx without success. If this is the most efficient way to access restricted data for use before/during WGDEC, then I would recommend a short training/walk through session is organised.  Alternatively, a short guidance document may suffice.  Happy to discuss.
