### ISSUE TITLE
Sample.ObservationDate conditional?

### ISSUE THREAD

**Issue by Osanna123** [ices-eg/wg_WGDEC#60]
ObservationDate is marked as conditional mandatory in the guidance/template, but what is the condition?
We were asked to get rid of the imprecise date flags like ND and U (http://vocab.ices.dk/?ref=1429), with a comment that at least a year should be available for reporting. 
Should the OservationDate become mandatory then?

**Comment by david9317** [comment]
I am happy for this to become mandatory.

**Comment by Osanna123** [comment]
Obs. date is mandatory from data call 2023-1
